export const AMQP_CONNECTION_OPTIONS = Symbol('AMQP_CONNECTION_OPTIONS')
export const AMQP_CONNECTION = Symbol('AMQP_CONNECTION')

export const PUBLISH_QUEUE_METADATA_TOKEN = Symbol('PUBLISH_QUEUE_METADATA')
export const PUBLISH_QUEUE_OPTIONS_METADATA_TOKEN = Symbol('PUBLISH_QUEUE_OPTIONS_METADATA')
export const PUBLISH_QUEUE_PRODUCER_METADATA_TOKEN = Symbol('PUBLISH_QUEUE_PRODUCER_METADATA')
