export const AMQP_CONNECTION_OPTIONS = Symbol('AMQP_CONNECTION_OPTIONS')
export const AMQP_CONNECTION = Symbol('AMQP_CONNECTION')

export const USE_AMQP_CONNECTION_TOKEN = Symbol('USE_AMQP_CONNECTION')

export const PUBLISH_EXCHANGE_METADATA_TOKEN = Symbol('PUBLISH_EXCHANGE_METADATA')
export const PUBLISH_EXCHANGE_OPTIONS_METADATA_TOKEN = Symbol('PUBLISH_EXCHANGE_OPTIONS_METADATA')
export const PUBLISH_EXCHANGE_PRODUCER_METADATA_TOKEN = Symbol('PUBLISH_EXCHANGE_PRODUCER_METADATA')
export const PUBLISH_EXCHANGE_CONTEXT_METADATA_TOKEN = Symbol('PUBLISH_EXCHANGE_CONTEXT_METADATA')

export const PUBLISH_QUEUE_METADATA_TOKEN = Symbol('PUBLISH_QUEUE_METADATA')
export const PUBLISH_QUEUE_PRODUCE_OPTIONS_METADATA_TOKEN = Symbol('PUBLISH_QUEUE_PRODUCE_OPTIONS_METADATA')
export const PUBLISH_QUEUE_PRODUCER_METADATA_TOKEN = Symbol('PUBLISH_QUEUE_PRODUCER_METADATA')
export const PUBLISH_QUEUE_CONTEXT_METADATA_TOKEN = Symbol('PUBLISH_QUEUE_CONTEXT_METADATA')

export const SUBSCRIBE_QUEUE_METADATA_TOKEN = Symbol('SUBSCRIBE_QUEUE_METADATA')
export const SUBSCRIBE_QUEUE_CONSUME_OPTIONS_METADATA_TOKEN = Symbol('SUBSCRIBE_QUEUE_CONSUME_OPTIONS_METADATA')
export const SUBSCRIBE_QUEUE_CONSUMER_METADATA_TOKEN = Symbol('SUBSCRIBE_QUEUE_CONSUMER_METADATA')
export const SUBSCRIBE_QUEUE_CONTEXT_METADATA_TOKEN = Symbol('SUBSCRIBE_QUEUE_CONTEXT_METADATA')
