name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      rabbitmq:
        image: rabbitmq:3-management
    container:
      image: node:lts
      env:
        CI: 'true'
        RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    steps:
      - name: SCM
        uses: actions/checkout@v2
      - name: Install Dependencies and Build
        run: |
          yarn
          yarn test:cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./reports/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
